[workspace]
resolver = "2"

members = [
  "packages/migrator",
  "packages/backend",
  "packages/catlog",
  "packages/catlog-wasm",
  "packages/migrator",
  "packages/notebook-types",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
