[package]
name = "catlog-wasm"
version = "0.1.0"
authors = ["Evan Patterson <evan@epatters.org>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
all-the-same = "1.1.0"
catlog = { path = "../catlog", features = ["ode", "serde-wasm"] }
console_error_panic_hook = { version = "0.1.7", optional = true }
derive_more = { version = "2", features = ["from", "try_into"] }
getrandom_v03 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
getrandom_v02 = { package = "getrandom", version = "0.2", features = ["js"] }
js-sys = "0.3.77"
nonempty = { version = "0.12", features = ["serialize"] }
notebook-types = { version = "0.1.0", path = "../notebook-types" }
serde = { version = "1", features = ["derive"] }
tsify = { version = "0.5", features = ["js"] }
ustr = "1"
uuid = { version = "1.18", features = ["v7", "rng-getrandom", "serde"] }
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3", features = ["console"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
