name = "CatColabInterop"
uuid = "9ecda8fb-39ab-46a2-a496-7285fa6368c1"
license = "MIT"
version = "0.1.1"
authors = ["CatColab team"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[weakdeps]
ACSets = "227ef7b5-1206-438b-ac65-934d6da304b8"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[extensions]
CatlabExt = ["Catlab", "ACSets"]

[compat]
Catlab = "0.17.2"
HTTP = "1.10.19"
MLStyle = "0.4.17"
Oxygen = "1.7.5"
Reexport = "1.2.2"
StructTypes = "1.11.0"
julia = "1.11"
