name = "AlgebraicJuliaService"
uuid = "9ecda8fb-39ab-46a2-a496-7285fa6368c1"
license = "MIT"
authors = ["CatColab team"]
version = "0.1.0"

[deps]
ACSets = "227ef7b5-1206-438b-ac65-934d6da304b8"
CombinatorialSpaces = "b1c52339-7909-45ad-8b6a-6e388f7c67f2"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Decapodes = "679ab3ea-c928-4fe6-8d59-fd451142d391"
DiagrammaticEquations = "6f00c28b-6bed-4403-80fa-30e0dc12f317"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ACSets = "0.2.21"
ComponentArrays = "0.15"
Debugger = "0.7.10"
Decapodes = "0.5.6"
DiagrammaticEquations = "0.1.7"
Distributions = "0.25"
GeometryBasics = "0.4"
JSON3 = "1"
LinearAlgebra = "1"
MLStyle = "0.4"
OrdinaryDiffEq = "6"
StaticArrays = "1"
