[package]
name = "notebook-types"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "migrate_examples"
path = "src/bin/migrate_examples.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.143"
tsify = { version = "0.5", features = ["js"] }
ustr = { version = "1.1.0", features = ["serde"] }
uuid = { version = "1.18", features = ["serde"] }
wasm-bindgen = "0.2.106"

[lints.clippy]
doc_paragraphs_missing_punctuation = "warn"
