[package]
name = "notebook-types"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nonempty = { version = "0.10", features = ["serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
tsify = { version = "0.5", features = ["js"] }
ustr = { version = "1.1.0", features = ["serde"] }
uuid = { version = "1.11", features = ["serde", "v7", "js"] }
wasm-bindgen = "0.2.100"
